### ISSUE TITLE
You have an awesome slider program that works great.  I have images that are vertically larger than the browser screen.  Is there a way to size the images so that that fit on the screen without scrolling?  Also, is there a way to size it to fit on a mobile device?   Thank you.

### ISSUE THREAD

**Issue by tooley333** [erik-krogh/SudoSlider#66]
Before anything else, make sure to update SudoSlider and jQuery to the latest version. Otherwise I will fart in your general direction, and maybe close the issue.

If your issue is an error report, make sure to include the following, or your issue will be ignored and/or closed
- A clear description of what happens.
- A clear description of what is supposed to happen.
- One of the following:
  - A link to a page where the issue is present (Like JSFiddle or similar).
  - A .zip file containing a page where the issue is present.

Yes, you really need to share a page, way to often the issues are due to some dependency, so you will be ignored if you don't.

**Comment by erik-krogh** [comment]
I think you can take a look at [the fullscreen demo](http://webbies.dk/assets/files/SudoSlider/package/demos/fullscreen.html).   

And possibly add a `body {overflow: hidden}` CSS rule.
