### ISSUE TITLE
bug sudo slider at chrom 88

### ISSUE THREAD

**Issue by Assiyahadaj** [erik-krogh/SudoSlider#67]
Hi ! 

The effect, slide of sudo slider doesn't work at the last version of chrome 88

Thank you!

**Comment by erik-krogh** [comment]
I tried out various effects in Chrome 88, and they all worked.  

So you'll have to be a bit more specific.   
Can you give a link to some page that is not working?

**Comment by makmic** [comment]
Hi there,
I'm having the same issues on multiple projects. It seems to be connected to the "autoHeight" option, but I cannot pin it down exactly to some line it the source code. Commenting out the contents of this function removes the issue (and functionality):
https://github.com/erik-krogh/SudoSlider/blob/master/js/jquery.sudoSlider.js#L710

My closest guess would be change in the CSS transition handling of Chrome 88, but they did not mention it in their release notes. Other libraries do not seem to be affected.

You can see the bug on the demo page:
* http://webbies.dk/assets/files/SudoSlider/package/demos/autoheight.html
* Works on Chrome 87 and Firefox, broken on Chrome 88 (any OS)

**Comment by erik-krogh** [comment]
Thanks, I can replicate it now :+1:  

Apparently the issue only exists if the height of each slide is different.   
I'll look into it. 

As a temporary workaround you can disable CSS animations by setting `useCSS: false`.   
Everything should look the same, but it uses jQuery animations instead of CSS animations.

**Comment by erik-krogh** [comment]
@Assiyahadaj @makmic 
I think I fixed the issue.  
I just released `3.5.1`, which changed how the `slide` animation works (that's the default animation). 

The demos are also updated, so [the autoheight demo](http://webbies.dk/assets/files/SudoSlider/package/demos/autoheight.html) should work now.

**Comment by makmic** [comment]
Thanks @erik-krogh! 3.5.1 works like a charm :heart: 
If I understand it correctly CSS animations are still used but with `margin` instead of `translate`?

**Comment by erik-krogh** [comment]
> If I understand it correctly CSS animations are still used but with `margin` instead of `translate`?

Yes.   

I think it should work just the same.
But I'm on a Linux machine right now, so I haven't tested many browsers.
I would be glad if you could confirm that your thing works well in many browsers.

**Comment by makmic** [comment]
I can confirm that the change works on every browser I tested via BrowserStack:
```
MacOs BigSur: Works on Safari, Firefox 74, Chrome 88
Ubuntu 20.04: Works on Chrome 88, Firefox
Windows 7: Works on IE11 ;-)
Android: Works on Chrome
iOS: Works on Safari
```

**Comment by erik-krogh** [comment]
> I can confirm that the change works on every browser I tested via BrowserStack

Great.   

I'll keep this issue open for a while, to make it easily visible to anyone else that might have the same issue.

**Comment by assiya-hadaj-viseo** [comment]
Hi erik , 
Thank you it worked correctly thank you very much
